
package wsimport.url;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldServiceService", targetNamespace = "http://blog.coderecord.org/", wsdlLocation = "http://localhost:8080/wsServer/wsservice/helloWorldService?wsdl")
public class HelloWorldServiceService
    extends Service
{

    private final static URL HELLOWORLDSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(wsimport.url.HelloWorldServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = wsimport.url.HelloWorldServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/wsServer/wsservice/helloWorldService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/wsServer/wsservice/helloWorldService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSERVICESERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldServiceService() {
        super(HELLOWORLDSERVICESERVICE_WSDL_LOCATION, new QName("http://blog.coderecord.org/", "HelloWorldServiceService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServicePort")
    public HelloWorldService getHelloWorldServicePort() {
        return super.getPort(new QName("http://blog.coderecord.org/", "HelloWorldServicePort"), HelloWorldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServicePort")
    public HelloWorldService getHelloWorldServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://blog.coderecord.org/", "HelloWorldServicePort"), HelloWorldService.class, features);
    }

}
